import Head from 'next/head'
import Link from 'next/link'
import {useRouter} from "next/router";
// import { Inter } from '@next/font/google'
// import styles from '@/styles/Home.module.css'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const router = useRouter();
  const handlePlaceOrder =()=>{
   alert("Order Placed")
   router.push("/products")

  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h2>This is Homepage</h2>
        <h2>
          <Link href="/blogs">
            Blogs
          </Link>
        </h2>
        <h2>
          <Link href="/products">
            Products
          </Link>
        </h2>
        <button onClick={handlePlaceOrder}>Palce Order</button>
      </main>
    </>
  )
}
