import Head from 'next/head';
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Pre-rendering</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{margin:"10px"}}>
        <h1>Next.Js pre-rendering</h1>
          <Link href="/users" passHref>
             <h3>Users</h3>
          </Link>
          <Link href="/posts" passHref>
              <h3>Posts</h3>
          </Link>
          <Link href="/products" passHref>
              <h3>Products</h3>
          </Link>
          <Link href="/events" passHref>
              <h3>Events</h3>
          </Link>

      </div>
    </>
  )
}
